dependencies {
    api project(':test-common-core')
    api project(':test-common-junit5')
    api "com.github.tomakehurst:wiremock-jre8:${wiremockVersion}"
    api "org.junit.jupiter:junit-jupiter:${junitJupiterVersion}"
    api "org.spockframework:spock-core:${spockVersion}"
    api "org.spockframework:spock-spring:${spockVersion}"
    api "org.apache.groovy:groovy-all:${groovyVersion}"

    compileOnly "org.springframework.boot:spring-boot-starter-web:${springBootVersion}"
    compileOnly "org.springframework.cloud:spring-cloud-starter-openfeign:3.1.8"

    testImplementation "org.springframework.boot:spring-boot-starter-test:${springBootVersion}"
    testImplementation "org.springframework.boot:spring-boot-starter-web:${springBootVersion}"
    testImplementation "org.springframework.cloud:spring-cloud-starter-openfeign:3.1.8"
}
