dependencies {
    api project(':test-infra-core')
    api project(':test-infra-junit5')
    api "org.mockito:mockito-core:${mockitoVersion}"
    api "org.testcontainers:junit-jupiter:${testcontainersVersion}"
    api "org.testcontainers:mongodb:${testcontainersVersion}"
    api "org.testcontainers:neo4j:${testcontainersVersion}"

    compileOnly "org.springframework.boot:spring-boot-starter-data-redis:${springBootVersion}"
    compileOnly "org.springframework.boot:spring-boot-starter-data-mongodb:${springBootVersion}"
    compileOnly "org.springframework.boot:spring-boot-starter-data-neo4j:${springBootVersion}"

    testImplementation "org.springframework.boot:spring-boot-starter-test:${springBootVersion}"
    testImplementation "org.springframework.boot:spring-boot-starter-data-redis:${springBootVersion}"
    testImplementation "org.apache.groovy:groovy-all:${groovyVersion}"
    testImplementation "org.spockframework:spock-core:${spockVersion}"
    testImplementation "org.spockframework:spock-spring:${spockVersion}"
}
