dependencies {
    api project(':test-infra-core')
    api project(':test-infra-junit5')
    api "org.testcontainers:elasticsearch:${testcontainersVersion}"
    api "org.testcontainers:junit-jupiter:${testcontainersVersion}"

    compileOnly "org.springframework.boot:spring-boot-starter-data-elasticsearch:${springBootVersion}"

    testImplementation "org.springframework.boot:spring-boot-starter-test:${springBootVersion}"
}
