rootProject.name = 'test-infra'

include 'test-infra-core'
include 'test-infra-spring-mvc'
include 'test-infra-orm'
include 'test-infra-orm:test-infra-jpa'
include 'test-infra-orm:test-infra-mybatis'
include 'test-infra-junit5'
include 'test-infra-spock'
include 'test-infra-storage-rdbms'
include 'test-infra-storage-nosql'
include 'test-infra-storage-search'
include 'test-infra-storage-file'
include 'test-infra-mq-broker'
include 'test-infra-http-mock'
include 'test-infra-rpc-mock'
include 'test-infra-schedule-mock'
include 'test-infra-all'
include 'test-infra-example'
