rootProject.name = 'test-common'

include 'test-common-core'
include 'test-common-spring-mvc'
include 'test-common-orm'
include 'test-common-orm:test-common-jpa'
include 'test-common-orm:test-common-mybatis'
include 'test-common-junit5'
include 'test-common-spock'
include 'test-common-storage-rdbms'
include 'test-common-storage-nosql'
include 'test-common-storage-search'
include 'test-common-storage-file'
include 'test-common-mq-broker'
include 'test-common-http-mock'
include 'test-common-rpc-mock'
include 'test-common-schedule-mock'
include 'test-common-all'
include 'test-common-example'
