dependencies {
    api project(':test-common-core')
    api project(':test-common-junit5')
    api "org.mockito:mockito-core:${mockitoVersion}"

    compileOnly "org.springframework.boot:spring-boot-starter-test:${springBootVersion}"
    compileOnly "com.xuxueli:xxl-job-core:2.4.0"
    compileOnly "org.quartz-scheduler:quartz:2.3.2"

    testImplementation "org.springframework.boot:spring-boot-starter-test:${springBootVersion}"
}
