dependencies {
    api project(':test-infra-core')
    api project(':test-infra-junit5')
    api project(':test-infra-spock')
    api project(':test-infra-storage-rdbms')
    api project(':test-infra-storage-nosql')
    api project(':test-infra-storage-search')
    api project(':test-infra-storage-file')
    api project(':test-infra-mq-broker')
    api project(':test-infra-http-mock')
    api project(':test-infra-rpc-mock')
    api project(':test-infra-schedule-mock')
}
