dependencies {
    compileOnly project(':test-infra-storage-rdbms')

    compileOnly "org.springframework.boot:spring-boot-starter:${springBootVersion}"
    compileOnly "org.mybatis.spring.boot:mybatis-spring-boot-starter:${mybatisSpringBootVersion}"
    compileOnly "org.mybatis.spring.boot:mybatis-spring-boot-starter-test:${mybatisSpringBootVersion}"

    // H2 - compileOnly for library consumers, testRuntimeOnly for our own tests
    compileOnly "com.h2database:h2:2.1.214"
    testRuntimeOnly "com.h2database:h2:2.1.214"

    testImplementation project(':test-infra-storage-rdbms')
    testImplementation "org.springframework.boot:spring-boot-starter:${springBootVersion}"
    testImplementation "org.mybatis.spring.boot:mybatis-spring-boot-starter:${mybatisSpringBootVersion}"
    testImplementation "org.mybatis.spring.boot:mybatis-spring-boot-starter-test:${mybatisSpringBootVersion}"
    testImplementation "com.mysql:mysql-connector-j:8.0.33"
}
