== Message Queue Module

`test-infra-mq-broker` provides RabbitMQ / Kafka / RocketMQ / Pulsar containers and mock utilities.

=== Maven Coordinates

[source,groovy,subs="attributes+"]
----
testImplementation 'io.github.wkaylves:test-infra-mq-broker:{infraVersion}'
----

=== Container Support

==== SharedRabbitMQContainer

RabbitMQ singleton container.

[source,java]
----
class RabbitMqIntegrationTest {
    @Container
    static RabbitMQContainer rabbit = SharedRabbitMQContainer.getInstance();
}
----

==== SharedKafkaContainer

Kafka singleton container.

[source,java]
----
class KafkaIntegrationTest {
    @Container
    static KafkaContainer kafka = SharedKafkaContainer.getInstance();
}
----

==== SharedRocketMQContainer

RocketMQ singleton container.

[source,java]
----
class RocketMqIntegrationTest {
    @Container
    static GenericContainer<?> rocketmq = SharedRocketMQContainer.getInstance();
}
----

==== SharedPulsarContainer

Pulsar singleton container.

[source,java]
----
class PulsarIntegrationTest {
    @Container
    static PulsarContainer pulsar = SharedPulsarContainer.getInstance();
}
----

=== MockRocketMQUtils

RocketMQ mock utility for pure Mockito scenarios.

[source,java]
----
RocketMQTemplate mqTemplate = MockRocketMQUtils.mockRocketMQTemplate();
// Use mqTemplate for testing
----

=== Container Singleton Summary

[cols="2,3",options="header"]
|===
|Class
|Description

|`SharedRabbitMQContainer`
|RabbitMQ singleton container

|`SharedKafkaContainer`
|Kafka singleton container

|`SharedRocketMQContainer`
|RocketMQ singleton container

|`SharedPulsarContainer`
|Pulsar singleton container

|`MockRocketMQUtils`
|RocketMQ mock utility
|===
