dependencies {
    implementation project(':test-common-core')
    implementation project(':test-common-junit5')
    implementation project(':test-common-spock')
    implementation project(':test-common-storage-rdbms')
    implementation project(':test-common-storage-nosql')
    implementation project(':test-common-mq-broker')
    implementation project(':test-common-http-mock')
    implementation project(':test-common-schedule-mock')

    implementation "org.springframework.boot:spring-boot-starter-web:${springBootVersion}"
    implementation "org.springframework.boot:spring-boot-starter-data-jpa:${springBootVersion}"
    implementation "org.springframework.boot:spring-boot-starter-data-redis:${springBootVersion}"
    implementation "org.mybatis.spring.boot:mybatis-spring-boot-starter:${mybatisSpringBootVersion}"
    implementation "mysql:mysql-connector-java:8.0.33"

    testImplementation "org.springframework.boot:spring-boot-starter-test:${springBootVersion}"
    testImplementation "org.apache.groovy:groovy-all:${groovyVersion}"
    testImplementation "org.spockframework:spock-spring:${spockVersion}"
    testImplementation "org.testcontainers:junit-jupiter:${testcontainersVersion}"
    testImplementation "org.testcontainers:mysql:${testcontainersVersion}"
}
