dependencies {
    api project(':test-infra-core')
    api project(':test-infra-junit5')
    api "org.testcontainers:junit-jupiter:${testcontainersVersion}"

    api "org.testcontainers:minio:${testcontainersVersion}"

    compileOnly "io.minio:minio:8.5.7"
    compileOnly "com.jcraft:jsch:0.1.55"
    compileOnly "commons-net:commons-net:3.9.0"

    testImplementation "org.springframework.boot:spring-boot-starter-test:${springBootVersion}"
}
